const TMEME = {
  COLOR: '#F89680',
  COLOR_PALETTE: [
    '#F89680',
    '#F5A623',
    '#F8E71C',
    '#50E3C2',
    '#4A90E2',
    '#7E1FD1'
  ],
  BACKGROUND_COLOR: '#ECECEC',
  THEME_BACKGROUND_COLOR: '#F9F5F3',
  ANDROID_FONT_FAMILY: 'Droid Sans Mono',
  ANDROID_TITLE_BAR_HEIGHT: 56,
  ANDROID_APP_TAB_BAR_HEIGHT: 52
};

export default TMEME;
