const TMEME = {
  COLOR: '#F89680',
  COLOR_PALETTE: [
    '#F89680',
    '#00D0AD',
    '#F76B9D',
    '#0794BF',
    '#F5A623'
  ],
  BACKGROUND_COLOR: '#FAF7F5',
  DARK_TEXT_COLOR: '#3B3A3B',
  LIGHT_TEXT_COLOR: '#FFFFFF',
  THEME_BACKGROUND_COLOR: '#F9F5F3',
  ANDROID_FONT_FAMILY: 'Droid Sans Mono',
  ANDROID_TITLE_BAR_HEIGHT: 56,
  ANDROID_APP_TAB_BAR_HEIGHT: 52
};

export default TMEME;
